// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB6cuAQgoJ8SgFb68i724xBWQpYyRw8-60',
    appId: '1:465395855132:web:b767e26575f3f0f24e94d9',
    messagingSenderId: '465395855132',
    projectId: 'medi-ghor-myflutterproject',
    authDomain: 'medi-ghor-myflutterproject.firebaseapp.com',
    storageBucket: 'medi-ghor-myflutterproject.appspot.com',
    measurementId: 'G-DB75H7TQ2C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAn-pepnl4XIMFfNWYs3HJrnVjQoBZSSE0',
    appId: '1:465395855132:android:b214956c7b6d89a14e94d9',
    messagingSenderId: '465395855132',
    projectId: 'medi-ghor-myflutterproject',
    storageBucket: 'medi-ghor-myflutterproject.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCl6pTdpislG2k5Gy3NZ34cEOaudNx6bpk',
    appId: '1:465395855132:ios:ff34ba007fe89c364e94d9',
    messagingSenderId: '465395855132',
    projectId: 'medi-ghor-myflutterproject',
    storageBucket: 'medi-ghor-myflutterproject.appspot.com',
    iosBundleId: 'com.example.mediGhor',
  );
}
